export const introEpisodes = [
    {
        title: "Coding Environment",
        image: "/waterfall.png",
        description: "Learn about the coding environment (foundry-rs, IDEs, CLI, etc.)",
        episodeVideo: "easy_1.mp4",
        solutionsVideo: "easy_2.mp4",
        episodeTimestamps: [
            { description: 'Introduction', timestampString: '0:15', timestampNumber: 15 },
            { description: 'int Type', timestampString: '0:45', timestampNumber: 45 },
            { description: 'uint Type', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'bool Type', timestampString: '3:55', timestampNumber: 235 },
            { description: 'bytes Type', timestampString: '4:55', timestampNumber: 295 },
        ],
        solutionsTimestamp: [
            { description: 'Puzzle A', timestampString: '0:15', timestampNumber: 15 },
            { description: 'Puzzle B', timestampString: '0:45', timestampNumber: 45 },
            { description: 'Puzzle C', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'Puzzle D', timestampString: '3:55', timestampNumber: 235 },
            { description: 'Puzzle E', timestampString: '4:55', timestampNumber: 295 },
        ],
    },
    {
        title: "Github",
        image: "/lotus.png",
        description: "Explore the fundamentals of Github for version control and branch management",
        episodeVideo: "easy_1.mp4",
        solutionsVideo: "easy_2.mp4",
        episodeTimestamps: [
            { description: 'Introduction', timestampString: '0:15', timestampNumber: 15 },
            { description: 'int Type', timestampString: '0:45', timestampNumber: 45 },
            { description: 'uint Type', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'bool Type', timestampString: '3:55', timestampNumber: 235 },
            { description: 'bytes Type', timestampString: '4:55', timestampNumber: 295 },
        ],
        solutionsTimestamp: [
            { description: 'Puzzle A', timestampString: '0:15', timestampNumber: 15 },
            { description: 'Puzzle B', timestampString: '0:45', timestampNumber: 45 },
            { description: 'Puzzle C', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'Puzzle D', timestampString: '3:55', timestampNumber: 235 },
            { description: 'Puzzle E', timestampString: '4:55', timestampNumber: 295 },
        ],
    },
    {
        title: "foundry-rs",
        image: "/pose.png",
        description: "A more thorough review of foundry-rs functionality and essential tools",
        episodeVideo: "easy_1.mp4",
        solutionsVideo: "easy_2.mp4",
        episodeTimestamps: [
            { description: 'Introduction', timestampString: '0:15', timestampNumber: 15 },
            { description: 'int Type', timestampString: '0:45', timestampNumber: 45 },
            { description: 'uint Type', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'bool Type', timestampString: '3:55', timestampNumber: 235 },
            { description: 'bytes Type', timestampString: '4:55', timestampNumber: 295 },
        ],
        solutionsTimestamp: [
            { description: 'Puzzle A', timestampString: '0:15', timestampNumber: 15 },
            { description: 'Puzzle B', timestampString: '0:45', timestampNumber: 45 },
            { description: 'Puzzle C', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'Puzzle D', timestampString: '3:55', timestampNumber: 235 },
            { description: 'Puzzle E', timestampString: '4:55', timestampNumber: 295 },
        ],
    },
]

export const easyEpisodes = [
    {
        title: "Introduction",
        image: "/pose2.png",
        description: "A brief overview of how this course works, and the different sections",
        episodeVideo: "easy_1.mp4",
        solutionsVideo: "easy_2.mp4",
        episodeTimestamps: [
            { description: 'Introduction', timestampString: '0:15', timestampNumber: 15 },
            { description: 'int Type', timestampString: '0:45', timestampNumber: 45 },
            { description: 'uint Type', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'bool Type', timestampString: '3:55', timestampNumber: 235 },
            { description: 'bytes Type', timestampString: '4:55', timestampNumber: 295 },
        ],
        solutionsTimestamp: [
            { description: 'Puzzle A', timestampString: '0:15', timestampNumber: 15 },
            { description: 'Puzzle B', timestampString: '0:45', timestampNumber: 45 },
            { description: 'Puzzle C', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'Puzzle D', timestampString: '3:55', timestampNumber: 235 },
            { description: 'Puzzle E', timestampString: '4:55', timestampNumber: 295 },
        ],
    },
    {
        title: "Fundamentals",
        image: "/school.png",
        description: "The absolute fundamentals of Solidity, an introduction to types",
        episodeVideo: "easy_1.mp4",
        solutionsVideo: "easy_2.mp4",
        episodeTimestamps: [
            { description: 'Introduction', timestampString: '0:15', timestampNumber: 15 },
            { description: 'int Type', timestampString: '0:45', timestampNumber: 45 },
            { description: 'uint Type', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'bool Type', timestampString: '3:55', timestampNumber: 235 },
            { description: 'bytes Type', timestampString: '4:55', timestampNumber: 295 },
        ],
        solutionsTimestamp: [
            { description: 'Puzzle A', timestampString: '0:15', timestampNumber: 15 },
            { description: 'Puzzle B', timestampString: '0:45', timestampNumber: 45 },
            { description: 'Puzzle C', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'Puzzle D', timestampString: '3:55', timestampNumber: 235 },
            { description: 'Puzzle E', timestampString: '4:55', timestampNumber: 295 },
        ],
    },
    {
        title: "Primitive Types",
        image: "/waterfall.png",
        description: "Examines the int, uint, bool, bytes, and other primitives",
        episodeVideo: "easy_1.mp4",
        solutionsVideo: "easy_2.mp4",
        episodeTimestamps: [
            { description: 'Introduction', timestampString: '0:15', timestampNumber: 15 },
            { description: 'int Type', timestampString: '0:45', timestampNumber: 45 },
            { description: 'uint Type', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'bool Type', timestampString: '3:55', timestampNumber: 235 },
            { description: 'bytes Type', timestampString: '4:55', timestampNumber: 295 },
        ],
        solutionsTimestamp: [
            { description: 'Puzzle A', timestampString: '0:15', timestampNumber: 15 },
            { description: 'Puzzle B', timestampString: '0:45', timestampNumber: 45 },
            { description: 'Puzzle C', timestampString: '2:55',  timestampNumber: 175 },
            { description: 'Puzzle D', timestampString: '3:55', timestampNumber: 235 },
            { description: 'Puzzle E', timestampString: '4:55', timestampNumber: 295 },
        ],
    }
];